# 텐서플로우 Dataset: repeat(), batch(), take()
    - https://deep-deep-deep.tistory.com/27



In [3]:
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  # 텐서플로가 첫 번째 GPU만 사용하도록 제한
  try:
    tf.config.experimental.set_visible_devices(gpus[5], 'GPU')
  except RuntimeError as e:
    # 프로그램 시작시에 접근 가능한 장치가 설정되어야만 합니다
    print(e)

In [4]:


def count(stop): 
    i = 0 
    while i<stop: 
        yield i 
        i += 1 
        
ds_counter = tf.data.Dataset.from_generator(count, args=[25], output_types=tf.int32, output_shapes = (), ) 
for count_batch in ds_counter.repeat().batch(8).take(10): 
    print(count_batch.numpy())



[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]
[24  0  1  2  3  4  5  6]
[ 7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22]
[23 24  0  1  2  3  4  5]
[ 6  7  8  9 10 11 12 13]
[14 15 16 17 18 19 20 21]
[22 23 24  0  1  2  3  4]


In [8]:
for count_batch in ds_counter.repeat(1):
    print(count_batch.numpy())


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [9]:
for count_batch in ds_counter.repeat(1).batch(5):
    print(count_batch.numpy())



[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [10]:
for count_batch in ds_counter.repeat(1).batch(5).take(2):
    print(count_batch.numpy())

[0 1 2 3 4]
[5 6 7 8 9]


In [14]:
for count_batch in ds_counter.repeat(1).take(10):
    print(count_batch.numpy())


0
1
2
3
4
5
6
7
8
9


In [15]:
for count_batch in ds_counter.repeat(1).take(10).batch(2):
    print(count_batch.numpy())



[0 1]
[2 3]
[4 5]
[6 7]
[8 9]


In [22]:
for i in ds_counter:
    print(i)
    print(i.numpy())

tf.Tensor(0, shape=(), dtype=int32)
0
tf.Tensor(1, shape=(), dtype=int32)
1
tf.Tensor(2, shape=(), dtype=int32)
2
tf.Tensor(3, shape=(), dtype=int32)
3
tf.Tensor(4, shape=(), dtype=int32)
4
tf.Tensor(5, shape=(), dtype=int32)
5
tf.Tensor(6, shape=(), dtype=int32)
6
tf.Tensor(7, shape=(), dtype=int32)
7
tf.Tensor(8, shape=(), dtype=int32)
8
tf.Tensor(9, shape=(), dtype=int32)
9
tf.Tensor(10, shape=(), dtype=int32)
10
tf.Tensor(11, shape=(), dtype=int32)
11
tf.Tensor(12, shape=(), dtype=int32)
12
tf.Tensor(13, shape=(), dtype=int32)
13
tf.Tensor(14, shape=(), dtype=int32)
14
tf.Tensor(15, shape=(), dtype=int32)
15
tf.Tensor(16, shape=(), dtype=int32)
16
tf.Tensor(17, shape=(), dtype=int32)
17
tf.Tensor(18, shape=(), dtype=int32)
18
tf.Tensor(19, shape=(), dtype=int32)
19
tf.Tensor(20, shape=(), dtype=int32)
20
tf.Tensor(21, shape=(), dtype=int32)
21
tf.Tensor(22, shape=(), dtype=int32)
22
tf.Tensor(23, shape=(), dtype=int32)
23
tf.Tensor(24, shape=(), dtype=int32)
24
